routes/web.php
<?php

use Illuminate\Support\Facades\Route;




//////////////////////////Admin Part start from here/////////////////////////////
/// Route::group([], function() {
//});
//
//Route::get('admin/dashboard',                       ['as' => 'admin.dashboard',  'uses' => 'Admin\DashboardController@index']);
//Route::get('admin/product',                         ['as' => 'admin.product', 'uses' => 'Admin\ProductController@index']);
//Route::get('admin/product/create',                  ['as' => 'admin.proeuct.create', 'uses' => 'Admin\ProductController@create']);
///Route::group(['prefix' => 'admin'], function() {
//
//});
///

Route::group(['prefix' => 'admin', 'as' =>'admin.', 'namespace' => 'Admin\\', 'middleware' => 'auth'], function() {
    Route::get('dashboard',                       ['as' => 'dashboard',         'uses' => 'DashboardController@index']);
    Route::get('profile',                         ['as' => 'profile',           'uses' => 'UserController@profile']);
    Route::post('profile',                        ['as' => 'profile.update',    'uses' => 'UserController@profileUpdate']);
    Route::get('product',                         ['as' => 'product',           'uses' => 'ProductController@index']);
    Route::get('product/create',                  ['as' => 'proeuct.create',     'uses' => 'ProductController@create']);

    Route::get('user',                            ['as' => 'user',              'uses' => 'UserController@index']);
    Route::get('user/show/{id}',                  ['as' => 'user.show',       'uses' => 'UserController@show']);
    Route::get('user/create',                     ['as' => 'user.create',       'uses' => 'UserController@create']);
    Route::get('user/store',                      ['as' => 'user.store',        'uses' => 'UserController@store']);
    Route::get('user/edit/{id}',                  ['as' => 'user.edit',         'uses' => 'UserController@edit']);
    Route::get('user/update/{id}',                ['as' => 'user.update',       'uses' => 'UserController@update']);
    Route::get('user/delete/{id}',                ['as' => 'user.delete',       'uses' => 'UserController@destroy']);


    Route::get('post',                            ['as' => 'post',              'uses' => 'PostController@index']);
    Route::get('post/create',                     ['as' => 'post.create',       'uses' => 'PostController@create']);
    Route::get('post/store',                      ['as' => 'post.store',        'uses' => 'PostController@store']);
    Route::get('post/edit/{id}',                  ['as' => 'post.edit',         'uses' => 'PostController@edit']);
    Route::get('post/update/{id}',                ['as' => 'post.update',       'uses' => 'PostController@update']);
    Route::get('post/delete/{id}',                ['as' => 'post.delete',       'uses' => 'PostController@destroy']);

    Route::get('tag',                            ['as' => 'tag',              'uses' => 'TagController@index']);
    Route::get('tag/create',                     ['as' => 'tag.create',       'uses' => 'TagController@create']);
    Route::post('tag/store',                     ['as' => 'tag.store',        'uses' => 'TagController@store']);
    Route::get('tag/edit/{id}',                  ['as' => 'tag.edit',         'uses' => 'TagController@edit']);
    Route::post('tag/update/{id}',               ['as' => 'tag.update',       'uses' => 'TagController@update']);
    Route::get('tag/delete/{id}',                ['as' => 'tag.delete',       'uses' => 'TagController@destroy']);

    Route::get('category',                       ['as' => 'category',              'uses' => 'CategoryController@index']);
    Route::get('category/show/{id}',             ['as' => 'category.show',         'uses' => 'CategoryController@show']);
    Route::get('category/create',                ['as' => 'category.create',       'uses' => 'CategoryController@create']);
    Route::post('category/store',                ['as' => 'category.store',        'uses' => 'CategoryController@store']);
    Route::get('category/edit/{id}',             ['as' => 'category.edit',         'uses' => 'CategoryController@edit']);
    Route::post('category/update/{id}',          ['as' => 'category.update',       'uses' => 'CategoryController@update']);
    Route::get('category/delete/{id}',           ['as' => 'category.delete',       'uses' => 'CategoryController@destroy']);

    Route::get('attribute-group',                ['as' => 'attribute-group',              'uses' => 'AttributeController@index']);
    Route::get('attribute-group/show/{id}',      ['as' => 'attribute-group.show',         'uses' => 'AttributeController@show']);
    Route::get('attribute-group/create',         ['as' => 'attribute-group.create',       'uses' => 'AttributeController@create']);
    Route::post('attribute-group/store',         ['as' => 'attribute-group.store',        'uses' => 'AttributeController@store']);
    Route::get('attribute-group/edit/{id}',      ['as' => 'attribute-group.edit',         'uses' => 'AttributeController@edit']);
    Route::post('attribute-group/update/{id}',   ['as' => 'attribute-group.update',       'uses' => 'AttributeController@update']);
    Route::get('attribute-group/delete/{id}',    ['as' => 'attribute-group.delete',       'uses' => 'AttributeController@destroy']);

    Route::get('slider',                          ['as' => 'slider',                        'uses' => 'SliderController@index']);
    Route::get('slider/show/{id}',                ['as' => 'slider.show',                   'uses' => 'SliderController@show']);
    Route::get('slider/create',                   ['as' => 'slider.create',                 'uses' => 'SliderController@create']);
    Route::post('slider/store',                   ['as' => 'slider.store',                  'uses' => 'SliderController@store']);
    Route::get('slider/edit/{id}',                ['as' => 'slider.edit',                   'uses' => 'SliderController@edit']);
    Route::post('slider/update/{id}',             ['as' => 'slider.update',                 'uses' => 'SliderController@update']);
    Route::get('slider/delete/{id}',              ['as' => 'slider.delete',                 'uses' => 'SliderController@destroy']);

    Route::get('page',                          ['as' => 'page',                        'uses' => 'PageController@index']);
    Route::get('page/show/{id}',                ['as' => 'page.show',                   'uses' => 'PageController@show']);
    Route::get('page/create',                   ['as' => 'page.create',                 'uses' => 'PageController@create']);
    Route::post('page/store',                   ['as' => 'page.store',                  'uses' => 'PageController@store']);
    Route::get('page/edit/{id}',                ['as' => 'page.edit',                   'uses' => 'PageController@edit']);
    Route::post('page/update/{id}',             ['as' => 'page.update',                 'uses' => 'PageController@update']);
    Route::get('page/delete/{id}',              ['as' => 'page.delete',                 'uses' => 'PageController@destroy']);

    Route::get('menu-section',                  ['as' => 'menu-section',                 'uses' => 'MenuSectionController@index']);
    Route::get('menu-section/edit/{id}',        ['as' => 'menu-section.edit',            'uses' => 'MenuSectionController@edit']);
    Route::post('menu-section/update/{id}',     ['as' => 'menu-section.update',          'uses' => 'MenuSectionController@update']);
    Route::post('menu-section/load-page-row',   ['as' => 'menu-section.load-page-row',    'uses' => 'MenuSectionController@loadPageRow']);

    Route::get('brand',                          ['as' => 'brand',                        'uses' => 'BrandController@index']);
    Route::get('brand/show/{id}',                ['as' => 'brand.show',                   'uses' => 'BrandController@show']);
    Route::get('brand/create',                   ['as' => 'brand.create',                 'uses' => 'BrandController@create']);
    Route::post('brand/store',                   ['as' => 'brand.store',                  'uses' => 'BrandController@store']);
    Route::get('brand/edit/{id}',                ['as' => 'brand.edit',                   'uses' => 'BrandController@edit']);
    Route::post('brand/update/{id}',             ['as' => 'brand.update',                 'uses' => 'BrandController@update']);
    Route::get('brand/delete/{id}',              ['as' => 'brand.delete',                 'uses' => 'BrandController@destroy']);

    Route::get('currency',                          ['as' => 'currency',                        'uses' => 'CurrencyController@index']);
    Route::get('currency/show/{id}',                ['as' => 'currency.show',                   'uses' => 'CurrencyController@show']);
    Route::get('currency/create',                   ['as' => 'currency.create',                 'uses' => 'CurrencyController@create']);
    Route::post('currency/store',                   ['as' => 'currency.store',                  'uses' => 'CurrencyController@store']);
    Route::get('currency/edit/{id}',                ['as' => 'currency.edit',                   'uses' => 'CurrencyController@edit']);
    Route::post('currency/update/{id}',             ['as' => 'currency.update',                 'uses' => 'CurrencyController@update']);
    Route::get('currency/delete/{id}',              ['as' => 'currency.delete',                 'uses' => 'CurrencyController@destroy']);
    Route::post('currency/reorder',                 ['as' => 'currency.reorder',                 'uses' => 'CurrencyController@reorder']);

});





// --------------------------------------Frontend Routes -------------------------

Auth::routes();

Route::get('/', 'Front\HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'first_name', 'middle_name', 'last_name', 'contact', 'address','created_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UserController extends BaseController
{

    public function profile()
    {
        $data = [];
        $data['user'] = auth()->user();
        return view(parent::loadCommonDataToView('admin.user.profile'), compact('data'));
    }

    public function profileUpdate(Request $request)
    {
        $this->validateLogin($request);


        $user = auth()->user();
        $user->name = $request->get('name');
        $user->first_name = $request->get('first_name');
        $user->middle_name = $request->get('middle_name');
        $user->last_name = $request->get('last_name');
        $user->contact = $request->get('contact');
        $user->address = $request->get('address');
        $user->email = $request->get('email');

        if($request->get('password')){
            $user->password = bcrypt($request->get('password'));
        }

        $user->save();

        $request->session()->flash('success_message', 'Profile Updated Successfully!');
        return redirect()->route('admin.profile');
    }

    protected function validateLogin(Request $request)
    {
        $rules = [
            'name' => 'required|string',Rule::unique('users')->ignore(auth()->user()->id),
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'email' => 'required|email',Rule::unique('users')->ignore(auth()->user()->id),
        ];
        if ($request->get('password')){
            $rules['password'] = 'required|string|min:6|confirmed';
        }

        $this->validate($request, $rules);

//        $this->validate($request, [
//            'name' => 'required|string',
//            'email' => 'required|email',
//            'password' => 'required|string|min:6|confirmed,
//        ]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['rows'] = User::select('id', 'email', 'first_name', 'middle_name', 'last_name', 'created_at')
            ->orderBy('id', 'desc')->paginate(10);


        return  view(parent::loadCommonDataToView('admin.user.index'), compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $data = [];
        $data['row'] = User::find($id);
        if (!$data['row'])
            return redirect()->route('admin.user');

        return  view(parent::loadCommonDataToView('admin.user.show'), compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/profile.blade.php
@extends('admin.includes.layout')

@section('title')
    User : Profile
@endsection

@section('content')
    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            <ul class="breadcrumb">
                @include('admin.includes.dashboard_breadcrumb_url')

                <li>
                    <a href="#">Forms</a>
                </li>
                <li class="active">Form Elements</li>
            </ul><!-- .breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off">
                        <i class="icon-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- #nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    Form Elements
                    <small>
                        <i class="icon-double-angle-right"></i>
                        Common form elements and layouts
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    @if(session()->has('success_message'))
                        <div class="alert alert-block alert-success">
                            <button type="button" class="close" data-dismiss="alert">
                                <i class="icon-remove"></i>
                            </button>

                            <p>
                                <strong>
                                    <i class="icon-ok"></i>
                                    Well done!
                                </strong>
                                {{ session()->get('success_message') }}
                            </p>

                        </div>
                    @endif
                    <form class="form-horizontal" role="form" method="post" action="{{ route('admin.profile.update') }}">
                        @csrf
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('name') ? 'has-error': '' }}" for="name-field-1"> User Name</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="name" value="{{ $data['user']->name }}" placeholder="Username" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('name') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('first_name') ? 'has-error': '' }}" for="name-field-1"> First Name</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="first_name" value="{{ $data['user']->first_name }}" placeholder="First Name" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('first_name'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('first_name') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>


                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('middle_name') ? 'has-error': '' }}" for="middle_name-field-1"> Middle Name</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="middle_name" value="{{ $data['user']->middle_name }}" placeholder="Middle Name" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('middle_name'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('middle_name') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('last_name') ? 'has-error': '' }}" for="last_name-field-1"> Last Name</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="last_name" value="{{ $data['user']->last_name }}" placeholder="Last Name" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('last_name'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('last_name') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('email') ? 'has-error': '' }}" for="name-field-1"> Email</label>

                            <div class="col-sm-9">
                                <input type="email" id="form-field-1" name="email" value="{{ $data['user']->email }}" placeholder="Email" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('email') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('contact') ? 'has-error': '' }}" for="last_name-field-1"> Contact</label>

                            <div class="col-sm-9">
                                <input type="number" id="form-field-1" name="contact" value="{{ $data['user']->contact }}" placeholder="Contact" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('contact'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('contact') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('address') ? 'has-error': '' }}" for="address-field-1"> Address</label>

                            <div class="col-sm-9">
                                <input type="text" id="form-field-1" name="contact" value="{{ $data['user']->address }}" placeholder="Address" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('address'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('address') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>
                        <hr>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right {{ $errors->has('password') ? 'has-error': '' }}" for="password"> Password</label>

                            <div class="col-sm-9">
                                <input type="password" id="form-field-1" name="password" placeholder="" class="col-xs-10 col-sm-5">
                            </div>
                            @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong></strong>{{ $errors->first('password') }}</strong>
                                </span>

                            @endif
                        </div>
                        <div class="space-4"></div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right" for="password_confirmation"> Confirm Password</label>

                            <div class="col-sm-9">
                                <input type="password" id="form-field-1" name="password_confirmation" placeholder="" class="col-xs-10 col-sm-5">
                            </div>
                        </div>
                        <div class="space-4"></div>

                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="submit">
                                    <i class="icon-ok bigger-110"></i>
                                    Update
                                </button>

                                <button class="btn" type="reset">
                                    <i class="icon-undo bigger-110"></i>
                                    Reset
                                </button>
                            </div>
                        </div>

                    </form>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
@endsection