routes/web.php
<?php

use Illuminate\Support\Facades\Route;




//////////////////////////Admin Part start from here/////////////////////////////
/// Route::group([], function() {
//});
//
//Route::get('admin/dashboard',                       ['as' => 'admin.dashboard',  'uses' => 'Admin\DashboardController@index']);
//Route::get('admin/product',                         ['as' => 'admin.product', 'uses' => 'Admin\ProductController@index']);
//Route::get('admin/product/create',                  ['as' => 'admin.proeuct.create', 'uses' => 'Admin\ProductController@create']);
///Route::group(['prefix' => 'admin'], function() {
//
//});
///

Route::group(['prefix' => 'admin', 'as' =>'admin.', 'namespace' => 'Admin\\', 'middleware' => 'auth'], function() {
    Route::get('dashboard',                       ['as' => 'dashboard',         'uses' => 'DashboardController@index']);
    Route::get('profile',                         ['as' => 'profile',           'uses' => 'UserController@profile']);
    Route::post('profile',                        ['as' => 'profile.update',    'uses' => 'UserController@profileUpdate']);
    Route::get('product',                         ['as' => 'product',           'uses' => 'ProductController@index']);
    Route::get('product/create',                  ['as' => 'proeuct.create',     'uses' => 'ProductController@create']);

    Route::get('user',                            ['as' => 'user',              'uses' => 'UserController@index']);
    Route::get('user/show/{id}',                  ['as' => 'user.show',       'uses' => 'UserController@show']);
    Route::get('user/create',                     ['as' => 'user.create',       'uses' => 'UserController@create']);
    Route::get('user/store',                      ['as' => 'user.store',        'uses' => 'UserController@store']);
    Route::get('user/edit/{id}',                  ['as' => 'user.edit',         'uses' => 'UserController@edit']);
    Route::get('user/update/{id}',                ['as' => 'user.update',       'uses' => 'UserController@update']);
    Route::get('user/delete/{id}',                ['as' => 'user.delete',       'uses' => 'UserController@destroy']);


    Route::get('post',                            ['as' => 'post',              'uses' => 'PostController@index']);
    Route::get('post/create',                     ['as' => 'post.create',       'uses' => 'PostController@create']);
    Route::get('post/store',                      ['as' => 'post.store',        'uses' => 'PostController@store']);
    Route::get('post/edit/{id}',                  ['as' => 'post.edit',         'uses' => 'PostController@edit']);
    Route::get('post/update/{id}',                ['as' => 'post.update',       'uses' => 'PostController@update']);
    Route::get('post/delete/{id}',                ['as' => 'post.delete',       'uses' => 'PostController@destroy']);

    Route::get('tag',                            ['as' => 'tag',              'uses' => 'TagController@index']);
    Route::get('tag/create',                     ['as' => 'tag.create',       'uses' => 'TagController@create']);
    Route::post('tag/store',                     ['as' => 'tag.store',        'uses' => 'TagController@store']);
    Route::get('tag/edit/{id}',                  ['as' => 'tag.edit',         'uses' => 'TagController@edit']);
    Route::post('tag/update/{id}',               ['as' => 'tag.update',       'uses' => 'TagController@update']);
    Route::get('tag/delete/{id}',                ['as' => 'tag.delete',       'uses' => 'TagController@destroy']);

    Route::get('category',                       ['as' => 'category',              'uses' => 'CategoryController@index']);
    Route::get('category/show/{id}',             ['as' => 'category.show',         'uses' => 'CategoryController@show']);
    Route::get('category/create',                ['as' => 'category.create',       'uses' => 'CategoryController@create']);
    Route::post('category/store',                ['as' => 'category.store',        'uses' => 'CategoryController@store']);
    Route::get('category/edit/{id}',             ['as' => 'category.edit',         'uses' => 'CategoryController@edit']);
    Route::post('category/update/{id}',          ['as' => 'category.update',       'uses' => 'CategoryController@update']);
    Route::get('category/delete/{id}',           ['as' => 'category.delete',       'uses' => 'CategoryController@destroy']);

    Route::get('attribute-group',                ['as' => 'attribute-group',              'uses' => 'AttributeController@index']);
    Route::get('attribute-group/show/{id}',      ['as' => 'attribute-group.show',         'uses' => 'AttributeController@show']);
    Route::get('attribute-group/create',         ['as' => 'attribute-group.create',       'uses' => 'AttributeController@create']);
    Route::post('attribute-group/store',         ['as' => 'attribute-group.store',        'uses' => 'AttributeController@store']);
    Route::get('attribute-group/edit/{id}',      ['as' => 'attribute-group.edit',         'uses' => 'AttributeController@edit']);
    Route::post('attribute-group/update/{id}',   ['as' => 'attribute-group.update',       'uses' => 'AttributeController@update']);
    Route::get('attribute-group/delete/{id}',    ['as' => 'attribute-group.delete',       'uses' => 'AttributeController@destroy']);

    Route::get('slider',                          ['as' => 'slider',                        'uses' => 'SliderController@index']);
    Route::get('slider/show/{id}',                ['as' => 'slider.show',                   'uses' => 'SliderController@show']);
    Route::get('slider/create',                   ['as' => 'slider.create',                 'uses' => 'SliderController@create']);
    Route::post('slider/store',                   ['as' => 'slider.store',                  'uses' => 'SliderController@store']);
    Route::get('slider/edit/{id}',                ['as' => 'slider.edit',                   'uses' => 'SliderController@edit']);
    Route::post('slider/update/{id}',             ['as' => 'slider.update',                 'uses' => 'SliderController@update']);
    Route::get('slider/delete/{id}',              ['as' => 'slider.delete',                 'uses' => 'SliderController@destroy']);

    Route::get('page',                          ['as' => 'page',                        'uses' => 'PageController@index']);
    Route::get('page/show/{id}',                ['as' => 'page.show',                   'uses' => 'PageController@show']);
    Route::get('page/create',                   ['as' => 'page.create',                 'uses' => 'PageController@create']);
    Route::post('page/store',                   ['as' => 'page.store',                  'uses' => 'PageController@store']);
    Route::get('page/edit/{id}',                ['as' => 'page.edit',                   'uses' => 'PageController@edit']);
    Route::post('page/update/{id}',             ['as' => 'page.update',                 'uses' => 'PageController@update']);
    Route::get('page/delete/{id}',              ['as' => 'page.delete',                 'uses' => 'PageController@destroy']);

    Route::get('menu-section',                  ['as' => 'menu-section',                 'uses' => 'MenuSectionController@index']);
    Route::get('menu-section/edit/{id}',        ['as' => 'menu-section.edit',            'uses' => 'MenuSectionController@edit']);
    Route::post('menu-section/update/{id}',     ['as' => 'menu-section.update',          'uses' => 'MenuSectionController@update']);
    Route::post('menu-section/load-page-row',   ['as' => 'menu-section.load-page-row',    'uses' => 'MenuSectionController@loadPageRow']);

    Route::get('brand',                          ['as' => 'brand',                        'uses' => 'BrandController@index']);
    Route::get('brand/show/{id}',                ['as' => 'brand.show',                   'uses' => 'BrandController@show']);
    Route::get('brand/create',                   ['as' => 'brand.create',                 'uses' => 'BrandController@create']);
    Route::post('brand/store',                   ['as' => 'brand.store',                  'uses' => 'BrandController@store']);
    Route::get('brand/edit/{id}',                ['as' => 'brand.edit',                   'uses' => 'BrandController@edit']);
    Route::post('brand/update/{id}',             ['as' => 'brand.update',                 'uses' => 'BrandController@update']);
    Route::get('brand/delete/{id}',              ['as' => 'brand.delete',                 'uses' => 'BrandController@destroy']);

    Route::get('currency',                          ['as' => 'currency',                        'uses' => 'CurrencyController@index']);
    Route::get('currency/show/{id}',                ['as' => 'currency.show',                   'uses' => 'CurrencyController@show']);
    Route::get('currency/create',                   ['as' => 'currency.create',                 'uses' => 'CurrencyController@create']);
    Route::post('currency/store',                   ['as' => 'currency.store',                  'uses' => 'CurrencyController@store']);
    Route::get('currency/edit/{id}',                ['as' => 'currency.edit',                   'uses' => 'CurrencyController@edit']);
    Route::post('currency/update/{id}',             ['as' => 'currency.update',                 'uses' => 'CurrencyController@update']);
    Route::get('currency/delete/{id}',              ['as' => 'currency.delete',                 'uses' => 'CurrencyController@destroy']);
    Route::post('currency/reorder',                 ['as' => 'currency.reorder',                 'uses' => 'CurrencyController@reorder']);

});





// --------------------------------------Frontend Routes -------------------------

Auth::routes();

Route::get('/', 'Front\HomeController@index')->name('home');

resources/views/admin/includes/breadcomes.blade.php
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

resources/views/admin/includes/header.blade.php
<div class="navbar navbar-default" id="navbar">
    <script type="text/javascript">
        try{ace.settings.check('navbar' , 'fixed')}catch(e){}
    </script>

    <div class="navbar-container" id="navbar-container">
        <div class="navbar-header pull-left">
            <a href="#" class="navbar-brand">
                <small>
                    <i class="icon-leaf"></i>
                    Ace Admin
                </small>
            </a><!-- /.brand -->
        </div><!-- /.navbar-header -->

        <div class="navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="grey">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-tasks"></i>
                        <span class="badge badge-grey">4</span>
                    </a>

                    <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-ok"></i>
                            4 Tasks to complete
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Software Update</span>
                                    <span class="pull-right">65%</span>
                                </div>

                                <div class="progress progress-mini ">
                                    <div style="width:65%" class="progress-bar "></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Hardware Upgrade</span>
                                    <span class="pull-right">35%</span>
                                </div>

                                <div class="progress progress-mini ">
                                    <div style="width:35%" class="progress-bar progress-bar-danger"></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Unit Testing</span>
                                    <span class="pull-right">15%</span>
                                </div>

                                <div class="progress progress-mini ">
                                    <div style="width:15%" class="progress-bar progress-bar-warning"></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Bug Fixes</span>
                                    <span class="pull-right">90%</span>
                                </div>

                                <div class="progress progress-mini progress-striped active">
                                    <div style="width:90%" class="progress-bar progress-bar-success"></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                See tasks with details
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="purple">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-bell-alt icon-animated-bell"></i>
                        <span class="badge badge-important">8</span>
                    </a>

                    <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-warning-sign"></i>
                            8 Notifications
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-pink icon-comment"></i>
												New Comments
											</span>
                                    <span class="pull-right badge badge-info">+12</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="btn btn-xs btn-primary icon-user"></i>
                                Bob just signed up as an editor ...
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-success icon-shopping-cart"></i>
												New Orders
											</span>
                                    <span class="pull-right badge badge-success">+8</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-info icon-twitter"></i>
												Followers
											</span>
                                    <span class="pull-right badge badge-info">+11</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                See all notifications
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="green">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-envelope icon-animated-vertical"></i>
                        <span class="badge badge-success">5</span>
                    </a>

                    <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-envelope-alt"></i>
                            5 Messages
                        </li>

                        <li>
                            <a href="#">
                                <img src="assets/avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                                <span class="msg-body">
											<span class="msg-title">
												<span class="blue">Alex:</span>
												Ciao sociis natoque penatibus et auctor ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>a moment ago</span>
											</span>
										</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="assets/avatars/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                                <span class="msg-body">
											<span class="msg-title">
												<span class="blue">Susan:</span>
												Vestibulum id ligula porta felis euismod ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>20 minutes ago</span>
											</span>
										</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="assets/avatars/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                                <span class="msg-body">
											<span class="msg-title">
												<span class="blue">Bob:</span>
												Nullam quis risus eget urna mollis ornare ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>3:15 pm</span>
											</span>
										</span>
                            </a>
                        </li>

                        <li>
                            <a href="inbox.html">
                                See all messages
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="light-blue">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="{{ asset('admin/assets/avatars/user.jpg') }}" alt="Jason's Photo" />
                        <span class="user-info">
									<small>Welcome,</small>
									Jason
								</span>

                        <i class="icon-caret-down"></i>
                    </a>

                    <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="#">
                                <i class="icon-cog"></i>
                                Settings
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('admin.profile') }}">
                                <i class="icon-user"></i>
                                Profile
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit()">
                                <i class="icon-off"></i>
                                Logout
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
            </ul><!-- /.ace-nav -->
        </div><!-- /.navbar-header -->
    </div><!-- /.container -->
</div>

resources/views/admin/includes/side_bar.blade.php
<div class="sidebar" id="sidebar">
    <script type="text/javascript">
        try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
                <i class="icon-signal"></i>
            </button>

            <button class="btn btn-info">
                <i class="icon-pencil"></i>
            </button>

            <button class="btn btn-warning">
                <i class="icon-group"></i>
            </button>

            <button class="btn btn-danger">
                <i class="icon-cogs"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div><!-- #sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li {!! request()->is('admin/dashboard')?'class="active"':'' !!}>
            <a href="{{ route('admin.dashboard') }}">
                <i class="icon-dashboard"></i>
                <span class="menu-text"> Dashboard </span>
            </a>
        </li>

        <li {!! request()->is('admin/post*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-desktop"></i>
                <span class="menu-text"> Post Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/post')?'class="active"':'' !!}>
                    <a href="{{ route('admin.post') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/post/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.post.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/user*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-user"></i>
                <span class="menu-text"> User Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/user')?'class="active"':'' !!}>
                    <a href="{{ route('admin.user') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/user/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.user.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/tag*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-list"></i>
                <span class="menu-text"> Tag Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/tag')?'class="active"':'' !!}>
                    <a href="{{ route('admin.tag') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/tag/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.tag.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/category*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-list"></i>
                <span class="menu-text"> Category Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/category')?'class="active"':'' !!}>
                    <a href="{{ route('admin.category') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/category/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.category.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/brand*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-list"></i>
                <span class="menu-text"> Brand Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/brand')?'class="active"':'' !!}>
                    <a href="{{ route('admin.brand') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/brand/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.brand.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/slider*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-list"></i>
                <span class="menu-text"> Slider Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/slider')?'class="active"':'' !!}>
                    <a href="{{ route('admin.slider') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/slider/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.slider.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/page*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-list"></i>
                <span class="menu-text"> Page Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/page')?'class="active"':'' !!}>
                    <a href="{{ route('admin.page') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/page/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.page.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/menu-section*')?'class="active"':'' !!}>
            <a href="{{ route('admin.menu-section') }}">
                <i class="icon-list"></i>
                <span class="menu-text"> Menu Manager </span>
            </a>
        </li>

        <li {!! request()->is('admin/attribute-group*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-list"></i>
                <span class="menu-text"> Attribute Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/attribute-group')?'class="active"':'' !!}>
                    <a href="{{ route('admin.attribute-group') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/attribute-group/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.attribute-group.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>

        <li {!! request()->is('admin/currency*')?'class="active"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-money"></i>
                <span class="menu-text"> Currency Manager </span>

                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/currency')?'class="active"':'' !!}>
                    <a href="{{ route('admin.currency') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>

                <li {!! request()->is('admin/currency/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.currency.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>
            </ul>
        </li>



    </ul><!-- /.nav-list -->

    <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
    </div>

    <script type="text/javascript">
        try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
    </script>
</div>